apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bookinfo
  namespace: library
spec:
  rules:
  - host: demo-kubernetes.info
    http:
      paths:
      - path: /productpage
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /login
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /logout
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /static/*
        backend:
          serviceName: productpage
          servicePort: 9080